Repository openshift/cluster-api-provider-kubemark, pull requests merged in 2019-07, with the labels that each got.

#23 Groom manifests
  config/controllers/deployment.yaml
  config/kustomization.yaml
Labels: approved, lgtm, size/XS

#24 Allow to specify machine deletion delay
  Makefile
  README.md
  pkg/actuators/machine/actuator.go
  pkg/apis/kubemarkproviderconfig/v1beta1/kubemarkmachineproviderconfig_types.go
  pkg/apis/kubemarkproviderconfig/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#25 Allow to override default kubemark node num cores and memory capacity
  README.md
  examples/machine-set-2a.yaml
  examples/machine.yaml
  pkg/actuators/machine/actuator.go
  pkg/apis/kubemarkproviderconfig/v1beta1/kubemarkmachineproviderconfig_types.go
  pkg/apis/kubemarkproviderconfig/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#26 Revendor openshift/kubernetes-drain to pick drain fix
  Gopkg.lock
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, lgtm, size/S
